image: ubuntu

environment:
  access_token:
    secure: fdd2f1bbc22dccd0df98d690ffafecb6dad0070f

install:
- pwsh: >- 
    Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser
    
    Install-Module -Name Pester -Force -Scope CurrentUser
    
build: off
test_script:
- pwsh: >- 

    Get-ChildItem -Path /home/appveyor/projects/pwshschool-tr7fa/ -recurse

    $Children = Get-ChildItem -Path /home/appveyor/projects/pwshschool-tr7fa/CI/
    
    $Children.Fullname
    
    Invoke-Expression $Children.Fullname
    
    $Module = (get-Item -Path /home/appveyor/projects/pwshschool-tr7fa/PWSHSchool.psd1).Fullname
    
    Import-Module $Module -Force


    Get-Module PWSHSchool
