image: ubuntu

environment:
  access_token:
    secure: fdd2f1bbc22dccd0df98d690ffafecb6dad0070f

install:
- pwsh: >- 
    Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser
    
    Install-Module -Name Pester -Force -Scope CurrentUser
    
    Import-Module ./PWSHSchool.psd1
    
   $res = Invoke-Pester -Path ./Tests -PassThru
